### ISSUE TITLE
Not working for German ID Cards (TD1) - Fix included

### ISSUE THREAD

**Issue by daniels7** [snifter/MRZCode.NET#1]
Hi,

this package is not working for German ID Cards (TD1) because the RegEx is partially wrong.
The RegEx for TD1FirstLine should be "([A|C|I][A-Z0-9<]{1})([A-Z<]{3})([A-Z0-9<]{9})([0-9]{1})([A-Z0-9<]{15})" and the RegEx for TD1SecondLine should be "([0-9]{6})([0-9]{1})([M|F|X|<]{1})([0-9]{6})([0-9]{1})([A-Z<]{3})([A-Z0-9<]{11})([0-9]{1})".

The reason is, that for the country string it can be up to 3 Letters, but it can be fewer as well. On German IDs the Country String would be "D<<" and not "DEU". That's why the RegEx has to accept "<" as input as well.

**Comment by daniels7** [comment]
I just saw that the same error affects TD2 and TD3 as well, so it should be corrected there as well. The Country/Nationality can always contain "<"

**Comment by daniels7** [comment]
I opened a pull request. You just have to merge it and bringt out an updated NuGet please.

**Comment by snifter** [comment]
Thank you for your conntribution! I've just released version included your patch in NuGet.
